version: '3.8'
services:
  db:
    container_name: "demo-pg"
    image: postgis/postgis:9.6-3.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=local
      - POSTGRES_DB=demo
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql